name: Checks on Pull Requests creation

on:
  pull_request:
    types: [opened, reopened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "prs"
  cancel-in-progress: true

jobs:
  analyzer:
    name: "Run lints"
    environment:
      name: general
    runs-on: ubuntu-latest
    env:
      GD_SECRETS: ${{ secrets.GD_SECRETS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Analyze
        run: |
          cd gordindev
          mkdir lib/keys && touch lib/keys/secrets.dart
          echo $GD_SECRETS | base64 -d > lib/keys/secrets.dart
          ../flutterw pub get
          ../flutterw analyze

  formatter:
    name: "Run formatter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify Formatting
        run: |
          cd gordindev
          ../flutterw pub get
          ../flutterw format --dry-run --set-exit-if-changed test_driver test lib tools integration_test

  goldens:
    name: "Check goldens"
    environment:
      name: general
    runs-on: ubuntu-latest
    env:
      GD_SECRETS: ${{ secrets.GD_SECRETS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Goldens
        run: |
          cd gordindev
          mkdir lib/keys && touch lib/keys/secrets.dart
          echo $GD_SECRETS | base64 -d > lib/keys/secrets.dart
          ../flutterw pub get
          ../flutterw test test/golden_tests/
